language: R

sudo: required

r_packages:
  - covr

apt_packages:
  - r-cran-rjags

notifications:
  email: false
  slack:
    rooms:
      - poissonconsulting:BKjfn7jsVh8zXTu2rq7BEQEb
    on_success: change
    on_failure: change
